# Generated by Django 2.2.9 on 2020-08-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('opt1', models.CharField(max_length=100)),
                ('opt2', models.CharField(max_length=100)),
                ('opt3', models.CharField(blank=True, max_length=100)),
                ('opt4', models.CharField(blank=True, max_length=100)),
                ('opt5', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Bada', models.IntegerField(default=0)),
                ('Possible', models.IntegerField(default=0)),
                ('Love', models.IntegerField(default=0)),
                ('Sobolo', models.IntegerField(default=0)),
                ('Small', models.IntegerField(default=0)),
                ('Math', models.IntegerField(default=0)),
                ('Meehee', models.IntegerField(default=0)),
                ('Antiseptic', models.IntegerField(default=0)),
                ('Because', models.IntegerField(default=0)),
                ('Jangma', models.IntegerField(default=0)),
                ('Lofi', models.IntegerField(default=0)),
                ('Blackleaf', models.IntegerField(default=0)),
                ('Fifteen', models.IntegerField(default=0)),
                ('Kind', models.IntegerField(default=0)),
                ('Station', models.IntegerField(default=0)),
                ('Nowrite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('poet', models.CharField(max_length=200)),
                ('img', models.URLField()),
                ('keyword', models.CharField(max_length=200)),
                ('result', models.TextField()),
                ('poem', models.TextField()),
                ('Plink', models.TextField()),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.Tester')),
            ],
        ),
    ]
