# Generated by Django 2.2.9 on 2020-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tester',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
