# Generated by Django 2.2.9 on 2020-08-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20200825_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='score',
        ),
        migrations.AddField(
            model_name='tester',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.Book'),
        ),
    ]
