# Generated by Django 2.2.9 on 2020-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20200826_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='content1',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='book',
            name='content2',
        ),
    ]
