# Generated by Django 2.2.9 on 2020-08-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20200828_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='opt1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt5',
            field=models.TextField(blank=True),
        ),
    ]
